spring:
  application:
    name: api-gateway
  data:
    redis:
      host: localhost
      port: 6379
      password: redis
      lettuce:
        pool:
          max-active: 8             # 최대 활성 연결 수
          max-idle: 8               # 최대 유휴 연결 수
          min-idle: 0               # 최소 유휴 연결 수
          time-between-eviction-runs: 10s  # 유휴 연결 검사 주기

server:
  port: 8080
