spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/service_c_db
    username: postgres
    password: postgres
  cloud:
    stream:
      function:
        bindings:
          processVoteData-in-0: input-topic
          sendAlertData-out-0: alert-topic
      bindings:
        input-topic:
          destination: service-c-topic
          group: service-c-group
          content-type: application/json
        alert-topic:
          destination: alert-topic
          content-type: application/json
      kafka:
        binder:
          brokers: localhost:9094

server:
  port: 8083
